# Generated by Django 6.0.5 on 2026-05-31 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('analysis_time', models.DateTimeField()),
                ('daily_bias', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=20)),
                ('h4_bias', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish'), ('neutral', 'Neutral')], max_length=20)),
                ('session', models.CharField(choices=[('london', 'London'), ('new_york', 'New York'), ('asia', 'Asia')], max_length=20)),
                ('zone_type', models.CharField(choices=[('ob', 'Order Block'), ('fvg', 'Fair Value Gap'), ('support_resistance', 'Support / Resistance'), ('none', 'None')], max_length=30)),
                ('has_liquidity_sweep', models.BooleanField(default=False)),
                ('confirmation', models.CharField(choices=[('choch', 'CHOCH'), ('bos', 'BOS'), ('none', 'None')], max_length=20)),
                ('rr', models.DecimalField(decimal_places=2, max_digits=4)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('decision', models.CharField(choices=[('trade', 'Trade'), ('wait', 'Wait'), ('no_trade', 'No Trade')], max_length=20)),
                ('reasons', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
