# Generated by Django 6.0.5 on 2026-07-20 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeanalysis',
            name='analysis_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
