# Generated by Django 6.0.5 on 2026-07-20 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0002_alter_tradeanalysis_analysis_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=12)),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=12)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('breakeven', 'Breakeven')], max_length=20)),
                ('profit_loss_r', models.DecimalField(decimal_places=2, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='analysis.tradeanalysis')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
